feat: 로그인 페이지 UI 개발
travelly-8/travelly-fe pull request #39
Opened 2024-05-24 14:41 UTC by Lv1GoM

## #️⃣ PR 타입

- [x] 기능 추가
- [ ] 버그 수정
- [ ] 의존성, 환경변수, 빌드 관련 코드 업데이트
- [ ] 기타 사소한 수정(디자인 등)

## 📝 작업 내용/변경 사항
📌 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능) 
> - 로그인 페이지 UI 개발
> - 로그인 회원가입 페이지 style 개발
> - 로그인 회원가입 페이지에서 사용되는 util함수 개발

### 스크린샷 (선택)

![로그인](https://github.com/travelly-8/travelly-fe/assets/143579803/a0036d8a-e56d-4b08-abb7-669eced3da93)

## 💬 리뷰 요구사항(선택)
📌 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> -
> -

##  💭 연관된 이슈(선택)
📌 #38

2024-05-24 14:54 UTC, innerstella requested changes

2024-05-24 14:59 UTC, Lv1GoM commented on src/styles/authStyles.tsx
로그인의 하위에 있으면 안되는건 아닌데 authStyles는 회원가입과 로그인페이지 양쪽에서 똑같이 사용하는 스타일이라서 styles폴더로 분리했습니다. 각각 로그인과 회원가입 폴더로 넣어도 되긴 합니다

2024-05-24 15:00 UTC, Lv1GoM commented on src/pages/login/login/index.tsx
> +      const filled: any = email && password && !document.querySelector('p')
저도 진짜 안쓰고 싶었어요.. 근데.. 진짜 잘 안돼서.. 시간날때 수정할게요..

2024-05-24 15:02 UTC, Lv1GoM commented on src/pages/login/login/index.tsx
> +      const filled: any = email && password && !document.querySelector('p')
모든 값이 다 존재한 상태로 유효성 검사 로직까지 통과해야 버튼이 활성화 되어야하는데, 유효성 검사 로직에 전부 통과했는지 검사하는거보다 p태그는 error메세지를 출력할때만 사용되어서 p태그가 없을때 전부 통과한걸로 처리하도록 한 것입니다

2024-05-24 15:02 UTC, Lv1GoM commented on src/pages/login/login/index.tsx
> +      </S.Header>
앗 넵

2024-05-24 15:04 UTC, Lv1GoM commented on src/pages/login/login/index.tsx
> +  }, [email, password])
둘중 하나의 코드를 먼저 작성하고 테스트했는데 뭔가 잘 되지 않아서 수정하다가 코드 중복이 일어난거같습니다. 수정하겠습니다

2024-05-24 15:06 UTC, innerstella commented on src/styles/authStyles.tsx
그런 이유라면 styles 폴더에 있어도 괜찮을 것 같습니다! 👍

2024-05-24 15:08 UTC, innerstella commented on src/pages/login/login/index.tsx
> +      const filled: any = email && password && !document.querySelector('p')
boolean 타입 안되나요?

2024-05-27 02:02 UTC, innerstella approved these changes

2024-05-27 02:06 UTC, merged